// Colour scheme actions.
export const CHANGE_COLOURS = 'CHANGE_COLOURS';

// Login page actions.
export const CHANGE_HOUSE = 'CHANGE_HOUSE';
export const CHANGE_YEAR = 'CHANGE_YEAR';

export const CHECK_IF_QUIZ_READY = 'CHECK_IF_QUIZ_READY';
export const QUIZ_IN_PROGRESS = 'QUIZ_IN_PROGRESS';
export const QUIZ_IS_SCHEDULED = 'QUIZ_IS_SCHEDULED';
export const NO_QUIZ_READY = 'NO_QUIZ_READY';

export const DELETE_QUIZ = 'DELETE_QUIZ';
export const DELETE_QUIZ_SUCCESS = 'DELETE_QUIZ_SUCCESS';
export const DELETE_QUIZ_FAILURE = 'DELETE_QUIZ_FAILURE';

export const REQUEST_QUIZZES = 'REQUEST_QUIZZES';
export const REQUEST_QUIZZES_FAILURE = 'REQUEST_QUIZZES_FAILURE';
export const RECEIVE_QUIZZES = 'RECEIVE_QUIZZES';

export const LEAVE_QUIZ = 'LEAVE_QUIZ';
export const LOAD_DEFAULT_QUIZ = 'LOAD_DEFAULT_QUIZ';
export const QUIZ_IS_READY = 'QUIZ_IS_READY';

// Quiz creator actions.
export const UPDATE_ID = 'UPDATE_ID';
export const UPDATE_TITLE = 'UPDATE_TITLE';
export const UPDATE_START_DATE = 'UPDATE_START_DATE';
export const UPDATE_START_TIME = 'UPDATE_START_TIME';
export const UPDATE_QUESTION_LENGTH = 'UPDATE_QUESTION_LENGTH';
export const UPDATE_BREAK_LENGTH = 'UPDATE_BREAK_LENGTH';
export const UPDATE_IS_FINISHED = 'UPDATE_IS_FINISHED';
export const UPDATE_ALL_SETTINGS = 'UPDATE_ALL_SETTINGS';

export const ADD_CATEGORY = 'ADD_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const EDIT_CATEGORY = 'EDIT_CATEGORY';
export const DELETE_ALL_CATEGORIES = 'DELETE_ALL_CATEGORIES';

export const ADD_QUESTION = 'ADD_QUESTION';
export const DELETE_QUESTION = 'DELETE_QUESTION';
export const EDIT_QUESTION = 'EDIT_QUESTION';
export const DELETE_ALL_QUESTIONS = 'DELETE_ALL_QUESTIONS';

export const ADD_ANSWER = 'ADD_ANSWER';
export const DELETE_ANSWER = 'DELETE_ANSWER';
export const EDIT_ANSWER = 'EDIT_ANSWER';
export const DELETE_ALL_ANSWERS = 'DELETE_ALL_ANSWERS';

export const UPLOAD_QUIZ = 'UPLOAD_QUIZ';

// Play quiz actions
export const BEGIN_QUIZ = 'BEGIN_QUIZ';
export const JOIN_QUIZ = 'JOIN_QUIZ';

export const DECREMENT_TIME_LEFT = 'DECREMENT_TIME_LEFT';
export const SHOW_NEXT_QUESTION = 'SHOW_NEXT_QUESTION';
export const MOVE_TO_CATEGORY = 'MOVE_TO_CATEGORY';

export const SELECT_ANSWER = 'SELECT_ANSWER';
export const RECEIVE_ANSWER = 'RECEIVE_ANSWER';
