// Login page actions.
export const CHANGE_HOUSE = 'CHANGE_HOUSE';
export const CHANGE_YEAR = 'CHANGE_YEAR';

export const REQUEST_QUIZZES = 'REQUEST_QUIZZES';
export const RECEIVE_QUIZZES = 'RECEIVE_QUIZZES';


// Quiz creator actions.
export const UPDATE_ID = 'UPDATE_ID';
export const UPDATE_TITLE = 'UPDATE_TITLE';
export const UPDATE_START_DATE = 'UPDATE_START_DATE';
export const UPDATE_START_TIME = 'UPDATE_START_TIME';
export const UPDATE_QUESTION_LENGTH = 'UPDATE_QUESTION_LENGTH';
export const UPDATE_BREAK_LENGTH = 'UPDATE_BREAK_LENGTH';

export const ADD_CATEGORY = 'ADD_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const EDIT_CATEGORY = 'EDIT_CATEGORY';

export const ADD_QUESTION = 'ADD_QUESTION';
export const DELETE_QUESTION = 'DELETE_QUESTION';
export const EDIT_QUESTION = 'EDIT_QUESTION';

export const ADD_ANSWER = 'ADD_ANSWER';
export const DELETE_ANSWER = 'DELETE_ANSWER';
export const EDIT_ANSWER = 'EDIT_ANSWER';

export const SAVE_QUIZ_SUCCESS = 'SAVE_QUIZ_SUCCESS';
export const SAVE_QUIZ_FAILURE = 'SAVE_QUIZ_FAILURE';
export const UPDATE_QUIZ_SUCCESS = 'UPDATE_QUIZ_SUCCESS';
export const UPDATE_QUIZ_FAILURE = 'UPDATE_QUIZ_FAILURE';
