export const UPDATE_TITLE = 'UPDATE_TITLE';
export const UPDATE_START_TIME = 'UPDATE_START_TIME';
export const UPDATE_QUESTION_INTERVALS = 'UPDATE_QUESTION_INTERVALS';
export const UPDATE_REALTIME_GRAPHICS = 'UPDATE_REALTIME_GRAPHICS';
export const UPDATE_INTERVAL_LENGTH = 'UPDATE_INTERVAL_LENGTH';

export const ADD_CATEGORY = 'ADD_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const EDIT_CATEGORY = 'EDIT_CATEGORY';

export const ADD_QUESTION = 'ADD_QUESTION';
export const DELETE_QUESTION = 'DELETE_QUESTION';
export const EDIT_QUESTION = 'EDIT_QUESTION';

export const ADD_ANSWER = 'ADD_ANSWER';
export const DELETE_ANSWER = 'DELETE_ANSWER';
export const EDIT_ANSWER = 'EDIT_ANSWER';
