const ADD_QUESTION = 'ADD_QUESTION';
const DELETE_QUESTION = 'DELETE_QUESTION';
const EDIT_QUESTION = 'EDIT_QUESTION'

const ADD_CATEGORY = 'ADD_CATEGORY';
const DELETE_CATEGORY = 'DELETE_CATEGORY';
const EDIT_CATEGORY = 'EDIT_CATEGORY';

const ADD_ANSWER = 'ADD_ANSWER';
const DELETE_ANSWER = 'DELETE_ANSWER';
const EDIT_ANSWER = 'EDIT_ANSWER';
