// Transforms the quiz structure generated by the
// creator into one that can be saved to the database.
const constructQuiz = quiz => ({
  ...quiz.settings,
  categories: quiz.categories.map(category => ({
    ...category,
    questions: quiz.questions.filter(question =>
      question.categoryId === category.id
    ).map(question => ({
      body: question.body,
      answers: quiz.answers.filter(answer =>
        answer.questionId === question.id
      ).map(answer => ({
        body: answer.body,
        correct: answer.correct
      }))
    }))
  }))
});

export default constructQuiz;
